// <auto-generated />
namespace train_tickets_system.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hopeFinal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hopeFinal));
        
        string IMigrationMetadata.Id
        {
            get { return "201512101106290_hopeFinal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
